baseURL = "http://ժապաւէն.հայ/"
#languageCode = "hy-AM"
title = "ժապաւէն"
theme = "nederburg"
#theme = "minimo"
email = "norayr@arnet.am"

[[menu.main]]
name = "հոսք"
url = "/"
weight = 1

#[[menu.main]]
#name = "հեղինակներ"
#url = "հեղինակ/համայնք/"
#weight = 2

[[menu.main]]
name = "մեր մասին"
url = "մեր_մասին/"
weight = 3

[[menu.main]]
name = "կապ"
url = "կապ/"
weight = 4


#[taxonomies]
#  category = "categories"
#  series = "series"
#  tag = "tags"
