baseURL = "http://ժապաւէն.հայ/"
languageCode = "hy-AM"
title = "ժապաւէն"
#theme = "octopress"
theme = "nederburg"
email = "norayr@arnet.am"
[taxonomies]
  category = "categories"
#  series = "series"
  tag = "tags"
